In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

pd.set_option('display.max_colwidth', None)

In [2]:
df_transaction_data = pd.read_csv('data/transaction_data.csv')
df_product = pd.read_csv('data/product.csv')
df_hh_demographic = pd.read_csv('data/hh_demographic.csv')
df_campaign_table = pd.read_csv('data/campaign_table.csv')
df_campaign_desc = pd.read_csv('data/campaign_desc.csv')
df_coupon = pd.read_csv('data/coupon.csv')
df_coupon_redempt = pd.read_csv('data/coupon_redempt.csv')
df_casual_data = pd.read_csv('data/causal_data.csv')

In [ ]:
# Dữ liệu giao dịch
# Ghi nhận chi tiết từng dòng sản phẩm được mua trên hóa đơn bán lẻ của hộ gia đình

# household_key: Mã định danh duy nhất cho từng hộ gia đình
# .
# basket_id: Mã định danh duy nhất cho mỗi lần mua sắm (lần đi chợ/siêu thị)
# .
# day: Ngày diễn ra giao dịch
# .
# product_id: Mã định danh duy nhất cho từng sản phẩm
# .
# quantity: Số lượng sản phẩm mua trong giao dịch
# .
# sales_value: Số tiền nhà bán lẻ nhận được từ giao dịch bán sản phẩm (sau khi đã trừ các khoản giảm giá)
# .
# store_id: Mã định danh cửa hàng
# .
# coupon_match_disc: Khoản giảm giá do nhà bán lẻ tài trợ khớp với coupon của nhà sản xuất
# .
# coupon_disc: Khoản giảm giá từ coupon của nhà sản xuất
# .
# retail_disc: Khoản giảm giá từ chương trình thẻ thành viên/thân thiết của nhà bán lẻ
# .
# trans_time: Thời gian trong ngày diễn ra giao dịch
# .
# week_no: Tuần diễn ra giao dịch (từ tuần 1 đến tuần 102)

print(df_transaction_data["TRANS_TIME"].max())
print(df_transaction_data["TRANS_TIME"].min())

df_transaction_data.head()

2359
0

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0

In [ ]:
# Thông tin sản phẩm
# Cung cấp thông tin phân loại danh mục và thương hiệu cho từng sản phẩm

# household_key: Mã định danh duy nhất cho từng hộ gia đình
# .
# basket_id: Mã định danh duy nhất cho mỗi lần mua sắm (lần đi chợ/siêu thị)
# .
# day: Ngày diễn ra giao dịch
# .
# product_id: Mã định danh duy nhất cho từng sản phẩm
# .
# quantity: Số lượng sản phẩm mua trong giao dịch
# .
# sales_value: Số tiền nhà bán lẻ nhận được từ giao dịch bán sản phẩm (sau khi đã trừ các khoản giảm giá)
# .
# store_id: Mã định danh cửa hàng
# .
# coupon_match_disc: Khoản giảm giá do nhà bán lẻ tài trợ khớp với coupon của nhà sản xuất
# .
# coupon_disc: Khoản giảm giá từ coupon của nhà sản xuất
# .
# retail_disc: Khoản giảm giá từ chương trình thẻ thành viên/thân thiết của nhà bán lẻ
# .
# trans_time: Thời gian trong ngày diễn ra giao dịch
# .
# week_no: Tuần diễn ra giao dịch (từ tuần 1 đến tuần 102)

print(df_product["DEPARTMENT"].unique())
df_product.head()

['GROCERY' 'MISC. TRANS.' 'PASTRY' 'DRUG GM' 'MEAT-PCKGD' 'SEAFOOD-PCKGD'
 'PRODUCE' 'NUTRITION' 'DELI' 'COSMETICS' 'MEAT' 'FLORAL'
 'TRAVEL & LEISUR' 'SEAFOOD' 'MISC SALES TRAN' 'SALAD BAR' 'KIOSK-GAS'
 'ELECT &PLUMBING' 'GRO BAKERY' 'GM MERCH EXP' 'FROZEN GROCERY'
 'COUP/STR & MFG' 'SPIRITS' 'GARDEN CENTER' 'TOYS' 'CHARITABLE CONT'
 'RESTAURANT' 'RX' 'PROD-WHS SALES' 'MEAT-WHSE' 'DAIRY DELI' 'CHEF SHOPPE'
 'HBC' 'DELI/SNACK BAR' 'PORK' 'AUTOMOTIVE' 'VIDEO RENTAL' ' '
 'CNTRL/STORE SUP' 'HOUSEWARES' 'POSTAL CENTER' 'PHOTO' 'VIDEO'
 'PHARMACY SUPPLY']

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [ ]:
# Thông tin nhân khẩu học hộ gia đình
# Chứa thông tin nhân khẩu học được mã hóa theo thứ tự logic của một bộ phận hộ gia đình trong nghiên cứu

# HOMEOWNER_DESC	Tình trạng sở hữu nhà của hộ gia đình, ví dụ nhóm thuê nhà / sở hữu nhà...
# KID_CATEGORY_DESC	Nhóm hộ gia đình theo tình trạng/số lượng trẻ em
df_hh_demographic.head()

,classification_1,classification_2,classification_3,HOMEOWNER_DESC,classification_5,classification_4,KID_CATEGORY_DESC,household_key
0,Age Group6,X,Level4,Homeowner,Group5,2,None/Unknown,1
1,Age Group4,X,Level5,Homeowner,Group5,2,None/Unknown,7
2,Age Group2,Y,Level3,Unknown,Group4,3,1,8
3,Age Group2,Y,Level6,Homeowner,Group4,4,2,13
4,Age Group4,Z,Level5,Homeowner,Group3,1,None/Unknown,16

In [14]:
df_hh_demographic['KID_CATEGORY_DESC'].unique()

array(['None/Unknown', '1', '2', '3+'], dtype=object)

In [ ]:
# Danh sách chiến dịch gửi đến hộ gia đình
# Liệt kê các chiến dịch tiếp thị mà từng hộ gia đình đã nhận được

df_campaign_table.head()

  DESCRIPTION  household_key  CAMPAIGN
0       TypeA             17        26
1       TypeA             27        26
2       TypeA            212        26
3       TypeA            208        26
4       TypeA            192        26

In [ ]:
# Thời gian diễn ra chiến dịch
# Quy định khoảng thời gian hiệu lực cho các chiến dịch tiếp thị

df_campaign_desc.head()

  DESCRIPTION  CAMPAIGN  START_DAY  END_DAY
0       TypeB        24        659      719
1       TypeC        15        547      708
2       TypeB        25        659      691
3       TypeC        20        615      685
4       TypeB        23        646      684

In [ ]:
# Thông tin coupon phát hành
# Liệt kê danh sách coupon được gửi trong từng chiến dịch và các sản phẩm hợp lệ được áp dụng coupon đó

# campaign: Mã chiến dịch tương ứng
# .
# coupon_upc: Mã định danh duy nhất của coupon
# .
# product_id: Mã sản phẩm mà coupon đó có thể áp dụng đổi thưởng
# .

df_coupon.head()

    COUPON_UPC  PRODUCT_ID  CAMPAIGN
0  10000089061       27160         4
1  10000089064       27754         9
2  10000089073       28897        12
3  51800009050       28919        28
4  52100000076       28929        25

In [5]:
duplicates = df_coupon[df_coupon.duplicated(keep=False)]

print(duplicates)

         COUPON_UPC  PRODUCT_ID  CAMPAIGN
47      54100010032       34214        27
49      54100010032       34214        27
50      54100010032       34214        27
51      54100010032       34214        27
124     54589314175       48728        27
126     54589314175       48728        27
127     54589314187       48728        27
128     54589314187       48728        27
129     54589314187       48728        27
130     54589314187       48728        27
131     54589314175       48728        27
132     54589314175       48728        27
253     51111122081       70714        27
254     51111122081       70714        27
257     51111122081       70714        27
258     51111122275       70714        27
259     51111122275       70714        27
260     51111122275       70714        27
261     51111122275       70714        27
262     51111122081       70714        27
273     54100024932       71794        27
274     54100024932       71794        27
275     54100024932       71794        27
276     54100024932       71794        27
285     53620010028       72290        27
286     53620010028       72290        27
287     53620010028       72290        27
288     53620010028       72290        27
321     51111131075       73681        27
322     51111131075       73681        27
323     51111131082       73681        27
324     51111131082       73681        27
325     51111131082       73681        27
326     51111131082       73681        27
327     51111131082       73681        27
328     51111131082       73681        27
329     51111131075       73681        27
330     51111131075       73681        27
331     51111131075       73681        27
332     51111131075       73681        27
354     54800110055       75637        27
355     54800110055       75637        27
356     54800110055       75637        27
357     54800110055       75637        27
369     54800110055       76487        27
370     54800110055       76487        27
371     54800110055       76487        27
436     53620010028       81353        27
437     53620010028       81353        27
438     53620010028       81353        27
439     53620010028       81353        27
440     53620010028       81353        27
453     53620010028       83153        27
454     53620010028       83153        27
457     53620010028       83153        27
458     53620010028       83153        27
473     54100010032       84511        27
474     54100010032       84511        27
475     54100010032       84511        27
476     54100010032       84511        27
477     54100010032       84511        27
478     54100010032       84511        27
487     53620010028       84957        27
488     53620010028       84957        27
489     53620010028       84957        27
491     53620010028       84957        27
507     53620010028       86148        27
508     53620010028       86148        27
509     53620010028       86148        27
510     53620010028       86148        27
511     53620010028       86148        27
516     57940011075       86354        27
517     57940011075       86354        27
518     57940011080       86354        27
519     57940011080       86354        27
520     57940011080       86354        27
521     57940011080       86354        27
522     57940011075       86354        27
523     57940011075       86354        27
526     53620010028       86378        27
527     53620010028       86378        27
528     53620010028       86378        27
529     53620010028       86378        27
540     53620010028       87639        27
541     53620010028       87639        27
542     53620010028       87639        27
543     53620010028       87639        27
544     53620010028       87639        27
550     54100027032       88223        27
551     54100027032       88223        27
552     54100027032       88223        27
554     54100027032       88223        27
555     54100027032       88223        27
557     54100027032       88914        27
560     54100027032       88914        27
561     54100027032       88914        27
562     54100027032       88914        27
569     53620010028       89337        27
570     53620010028       89337        27
571     53620010028       89337        27
572     53620010028       89337        27
591     54100027032       90473        27
592     54100027032       90473        27
593     54100027032       90473        27
594     54100027032       90473        27
610     53620010028       92436        27
611     53620010028       92436        27
612     53620010028       92436        27
613     53620010028       92436        27
614     53620010028       92436        27
615     53620010028       92436        27
616     53620010028       92436        27
617     53620010028       92436        27
685     57940011075       98090        27
686     57940011075       98090        27
687     57940011080       98090        27
688     57940011080       98090        27
689     57940011080       98090        27
690     57940011080       98090        27
691     57940011075       98090        27
692     57940011075       98090        27
757     54060060055      106293        27
758     54060060055      106293        27
760     54060060055      106293        27
761     54060060055      106293        27
784     57940011075      109347        27
785     57940011075      109347        27
786     57940011080      109347        27
787     57940011080      109347        27
788     57940011080      109347        27
789     57940011080      109347        27
790     57940011080      109347        27
791     57940011080      109347        27
792     57940011075      109347        27
793     57940011075      109347        27
794     57940011075      109347        27
795     57940011075      109347        27
799     53620010028      110183        27
800     53620010028      110183        27
801     53620010028      110183        27
803     54100027032      110469        27
804     54100027032      110469        27
805     54100027032      110469        27
806     54100027032      110469        27
809     54100027032      110469        27
825     54100025324      114642        27
826     54100025324      114642        27
827     54100025324      114642        27
828     54100025324      114642        27
831     57940011075      114877        27
832     57940011075      114877        27
833     57940011075      114877        27
834     57940011080      114877        27
835     57940011080      114877        27
836     57940011080      114877        27
837     57940011080      114877        27
838     57940011080      114877        27
839     57940011080      114877        27
840     57940011080      114877        27
841     57940011075      114877        27
842     57940011075      114877        27
843     57940011075      114877        27
844     57940011075      114877        27
848     57940011075      115969        27
849     57940011075      115969        27
850     57940011080      115969        27
851     57940011080      115969        27
852     57940011080      115969        27
853     57940011080      115969        27
854     57940011080      115969        27
855     57940011075      115969        27
856     57940011075      115969        27
857     57940011075      115969        27
858     57940011075      115969        27
859     57940011080      115969        27
860     57940011080      115969        27
861     57940011080      115969        27
862     57940011075      115969        27
863     57940011075      115969        27
866     54100025324      116715        27
867     54100025324      116715        27
868     54100025324      116715        27
869     54100025324      116715        27
873     54800110055      116799        27
874     54800110055      116799        27
875     54800110055      116799        27
876     54800110055      116799        27
877     54800110055      116799        27
883     54800110055      118224        27
884     54800110055      118224        27
885     54800110055      118224        27
887     54800110055      118224        27
902     57940011075      122223        27
903     57940011075      122223        27
904     57940011080      122223        27
905     57940011080      122223        27
906     57940011080      122223        27
907     57940011080      122223        27
908     57940011075      122223        27
909     57940011075      122223        27
915     57940011075      122958        27
916     57940011075      122958        27
917     57940011075      122958        27
918     57940011080      122958        27
919     57940011080      122958        27
920     57940011080      122958        27
921     57940011080      122958        27
922     57940011080      122958        27
923     57940011080      122958        27
924     57940011075      122958        27
925     57940011075      122958        27
926     57940011075      122958        27
934     57940011080      123690        27
935     57940011080      123690        27
936     57940011080      123690        27
937     57940011080      123690        27
938     57940011075      123690        27
939     57940011075      123690        27
940     57940011075      123690        27
941     57940011075      123690        27
942     57940011075      123690        27
943     57940011080      123690        27
973     57940011075      143538        27
974     57940011080      143538        27
975     57940011080      143538        27
976     57940011080      143538        27
977     57940011080      143538        27
978     57940011080      143538        27
979     57940011075      143538        27
980     57940011075      143538        27
981     57940011075      143538        27
982     57940011075      143538        27
983     57940011080      143538        27
984     57940011075      143538        27
1060    54589314187      265230        27
1061    54589314187      265230        27
1062    54589314187      265230        27
1063    54589314187      265230        27
1065    54589314175      265230        27
1066    54589314175      265230        27
1067    54589314175      265230        27
1068    54589314175      265230        27
1089    57940042076      288763        27
1090    57940042076      288763        27
1091    57940042055      288763        27
1092    57940042055      288763        27
1093    57940042055      288763        27
1094    57940042055      288763        27
1095    57940042076      288763        27
1096    57940042076      288763        27
1105    57940042076      302427        27
1106    57940042076      302427        27
1107    57940042055      302427        27
1108    57940042055      302427        27
1109    57940042055      302427        27
1110    57940042055      302427        27
1111    57940042076      302427        27
1112    57940042076      302427        27
1198    57940011075      420859        27
1201    57940011075      420859        27
1202    57940011075      420859        27
1203    57940011080      420859        27
1204    57940011080      420859        27
1205    57940011080      420859        27
1206    57940011080      420859        27
1207    57940011080      420859        27
1208    57940011080      420859        27
1209    57940011075      420859        27
1210    57940011075      420859        27
1211    57940011075      420859        27
1224    57940018076      431906        27
1225    57940018081      431906        27
1226    57940018081      431906        27
1227    57940018081      431906        27
1228    57940018081      431906        27
1229    57940018076      431906        27
1230    57940018076      431906        27
1232    57940018076      431906        27
1254    54100027032      442472        27
1255    54100027032      442472        27
1256    54100027032      442472        27
1257    54100027032      442472        27
1258    54100027032      442472        27
1305    57940011075      480004        27
1306    57940011075      480004        27
1307    57940011080      480004        27
1308    57940011080      480004        27
1309    57940011080      480004        27
1310    57940011080      480004        27
1311    57940011075      480004        27
1312    57940011075      480004        27
1417    51111131082      540176        27
1418    51111131082      540176        27
1419    51111131075      540176        27
1420    51111131075      540176        27
1421    51111131075      540176        27
1422    51111131075      540176        27
1423    51111131075      540176        27
1424    51111131075      540176        27
1425    51111131075      540176        27
1426    51111131082      540176        27
1427    51111131082      540176        27
1428    51111131082      540176        27
1429    51111131082      540176        27
1430    51111131082      540176        27
1431    51111131082      540176        27
1435    51111131075      540176        27
1451    53620010028      551731        27
1454    53620010028      551731        27
1455    53620010028      551731        27
1456    53620010028      551731        27
1468    53620010028      561604        27
1469    53620010028      561604        27
1470    53620010028      561604        27
1471    53620010028      561604        27
1472    53620010028      561604        27
1478    57940011075      562396        27
1479    57940011075      562396        27
1480    57940011080      562396        27
1481    57940011080      562396        27
1482    57940011080      562396        27
1483    57940011080      562396        27
1484    57940011075      562396        27
1485    57940011075      562396        27
1497    53620010028      565107        27
1498    53620010028      565107        27
1499    53620010028      565107        27
1500    53620010028      565107        27
1501    53620010028      565107        27
1531    54589314187      594966        27
1532    54589314187      594966        27
1533    54589314175      594966        27
1534    54589314175      594966        27
1535    54589314175      594966        27
1536    54589314187      594966        27
1537    54589314187      594966        27
1538    54589314175      594966        27
1542    54100024932      599484        27
1543    54100024932      599484        27
1544    54100024932      599484        27
1545    54100024932      599484        27
1561    51111131075      614196        27
1562    51111131075      614196        27
1563    51111131075      614196        27
1564    51111131082      614196        27
1565    51111131082      614196        27
1566    51111131082      614196        27
1567    51111131082      614196        27
1568    51111131082      614196        27
1569    51111131082      614196        27
1570    51111131075      614196        27
1571    51111131075      614196        27
1572    51111131075      614196        27
1602    53620010028      635053        27
1603    53620010028      635053        27
1604    53620010028      635053        27
1606    53620010028      635053        27
1607    53620010028      635053        27
1624    54100027032      648805        27
1625    54100027032      648805        27
1626    54100027032      648805        27
1627    54100027032      648805        27
1645    53620010028      654886        27
1646    53620010028      654886        27
1647    53620010028      654886        27
1648    53620010028      654886        27
1679    53620010028      680468        27
1680    53620010028      680468        27
1681    53620010028      680468        27
1682    53620010028      680468        27
1714    54100027032      707657        27
1715    54100027032      707657        27
1716    54100027032      707657        27
1717    54100027032      707657        27
1718    54100027032      707657        27
1723    54800110055      707871        27
1724    54800110055      707871        27
1725    54800110055      707871        27
1734    57940011075      722562        27
1735    57940011075      722562        27
1736    57940011080      722562        27
1737    57940011080      722562        27
1738    57940011080      722562        27
1739    57940011080      722562        27
1740    57940011075      722562        27
1741    57940011075      722562        27
1760    54100027032      734683        27
1761    54100027032      734683        27
1762    54100027032      734683        27
1763    54100027032      734683        27
1771    57940042076      742873        27
1772    57940042076      742873        27
1775    57940042076      742873        27
1776    57940042055      742873        27
1777    57940042055      742873        27
1778    57940042055      742873        27
1779    57940042055      742873        27
1780    57940042076      742873        27
1807    54100025324      768705        27
1808    54100025324      768705        27
1809    54100025324      768705        27
1810    54100025324      768705        27
1818    57940011075      772733        27
1819    57940011075      772733        27
1820    57940011075      772733        27
1821    57940011080      772733        27
1822    57940011080      772733        27
1823    57940011080      772733        27
1824    57940011080      772733        27
1825    57940011080      772733        27
1826    57940011075      772733        27
1827    57940011075      772733        27
1863    54100024932      810969        27
1864    54100024932      810969        27
1865    54100024932      810969        27
1866    54100024932      810969        27
1867    54100024932      810969        27
1882    53620010028      819063        27
1883    53620010028      819063        27
1884    53620010028      819063        27
1885    53620010028      819063        27
1891    53620010028      819304        27
1892    53620010028      819304        27
1893    53620010028      819304        27
1894    53620010028      819304        27
1895    53620010028      819304        27
1934    57940042076      821134        27
1935    57940042055      821134        27
1936    57940042055      821134        27
1937    57940042055      821134        27
1938    57940042055      821134        27
1939    57940042076      821134        27
1940    57940042076      821134        27
1941    57940042076      821134        27
1949    54100025324      821368        27
1950    54100025324      821368        27
1951    54100025324      821368        27
1956    57940018076      821863        27
1957    57940018081      821863        27
1958    57940018081      821863        27
1959    57940018081      821863        27
1960    57940018081      821863        27
1961    57940018076      821863        27
1962    57940018076      821863        27
1963    57940018076      821863        27
1977    53620010028      822483        27
1978    53620010028      822483        27
1979    53620010028      822483        27
1980    53620010028      822483        27
1981    53620010028      822483        27
1982    53620010028      822483        27
1994    57940018076      823349        27
1995    57940018076      823349        27
1997    57940018076      823349        27
1998    57940018076      823349        27
1999    57940018081      823349        27
2000    57940018081      823349        27
2001    57940018081      823349        27
2002    57940018081      823349        27
2003    57940018081      823349        27
2004    57940018081      823349        27
2005    57940018076      823349        27
2006    57940018076      823349        27
2039    54800110055      825123        27
2040    54800110055      825123        27
2041    54800110055      825123        27
2042    54800110055      825123        27
2043    54800110055      825123        27
2049    57940042055      825391        27
2053    57940042055      825391        27
2054    57940042055      825391        27
2055    57940042055      825391        27
2061    51111124081      825450        27
2062    51111124076      825450        27
2063    51111124076      825450        27

In [8]:
print(
    df_coupon.sort_values(
        by=["CAMPAIGN", "COUPON_UPC", "PRODUCT_ID"]
    )
)

         COUPON_UPC  PRODUCT_ID  CAMPAIGN
27      51111030050       32387         1
31      51111030050       32805         1
34      51111030050       33198         1
1578    51111030050      617450         1
1613    51111030050      639121         1
3885    51111030050      896085         1
4326    51111030050      916993         1
7460    51111030050     1037332         1
7891    51111030050     1056509         1
10341   51111030050     1198708         1
10441   51111030050     1225869         1
10711   51111030050     1303589         1
11010   51111030050     1405495         1
11248   51111030050     1546881         1
11533   51111030050     1692686         1
11920   51111030050     1846094         1
11930   51111030050     1853330         1
12228   51111030050     1976188         1
12365   51111030050     2037968         1
12731   51111030050     2403912         1
13092   51111030050     2991358         1
160     51380040009       61169         1
4697    51380040009      930918         1
9038    51380040009     1098186         1
11569   51380040009     1718800         1
11750   51380040009     1794764         1
16458   51380040009     8357418         1
16557   51380040009     8358383         1
16580   51380040009     8364862         1
16599   51380040009     9194206         1
16606   51380040009     9194383         1
16625   51380040009     9195089         1
16628   51380040009     9196920         1
16631   51380040009     9198613         1
20235   51380040009    13115500         1
574     52100012050       89509         1
1136    52100012050      359526         1
1137    52100012050      359707         1
1315    52100012050      480180         1
1704    52100012050      700057         1
5685    52100012050      965766         1
5955    52100012050      976059         1
7159    52100012050     1025641         1
8861    52100012050     1092040         1
10218   52100012050     1160482         1
11379   52100012050     1610376         1
11633   52100012050     1740877         1
11753   52100012050     1795553         1
12789   52100012050     2483149         1
13174   52100012050     3798594         1
8       52100020075       28929         1
13      52100020075       29096         1
42      52100020075       34180         1
54      52100020075       34331         1
65      52100020075       34776         1
214     52100020075       68168         1
222     52100020075       68862         1
235     52100020075       69982         1
577     52100020075       89519         1
660     52100020075       94994         1
725     52100020075      101922         1
747     52100020075      105237         1
1325    52100020075      487367         1
1359    52100020075      508844         1
1375    52100020075      516416         1
1412    52100020075      536338         1
1443    52100020075      545936         1
1519    52100020075      577103         1
1842    52100020075      795110         1
2198    52100020075      831447         1
2205    52100020075      831509         1
2475    52100020075      842140         1
2541    52100020075      844932         1
2545    52100020075      844991         1
3024    52100020075      862854         1
3472    52100020075      880377         1
3668    52100020075      888275         1
3717    52100020075      889989         1
4347    52100020075      917517         1
4814    52100020075      934156         1
5042    52100020075      940766         1
6224    52100020075      990656         1
6298    52100020075      992986         1
6411    52100020075      998328         1
6526    52100020075     1002516         1
6824    52100020075     1013503         1
6987    52100020075     1020032         1
7296    52100020075     1030342         1
7545    52100020075     1040784         1
7604    52100020075     1043837         1
7763    52100020075     1049918         1
8322    52100020075     1073775         1
8584    52100020075     1082544         1
8911    52100020075     1093113         1
9077    52100020075     1100124         1
9463    52100020075     1115577         1
9725    52100020075     1124475         1
9738    52100020075     1125123         1
10388   52100020075     1212054         1
10446   52100020075     1226408         1
10699   52100020075     1299065         1
11122   52100020075     1439608         1
11269   52100020075     1558546         1
11319   52100020075     1587022         1
11549   52100020075     1704583         1
11696   52100020075     1775420         1
11781   52100020075     1802518         1
11809   52100020075     1816494         1
11837   52100020075     1828522         1
11981   52100020075     1875761         1
11990   52100020075     1878907         1
11999   52100020075     1880641         1
12120   52100020075     1923791         1
12240   52100020075     1987955         1
12355   52100020075     2027206         1
12488   52100020075     2107433         1
12518   52100020075     2149717         1
12663   52100020075     2341187         1
12739   52100020075     2413077         1
12845   52100020075     2539940         1
12978   52100020075     2660052         1
13005   52100020075     2671436         1
13140   52100020075     3566906         1
13143   52100020075     3615921         1
13149   52100020075     3679915         1
13202   52100020075     3923684         1
14479   52100020075     6463727         1
17048   52100020075     9420140         1
17093   52100020075     9425312         1
19256   52100020075    12385374         1
19262   52100020075    12385375         1
19311   52100020075    12386123         1
162     52400000031       61385         1
167     52400000031       62904         1
178     52400000031       64551         1
223     52400000031       68869         1
266     52400000031       71198         1
282     52400000031       72013         1
296     52400000031       72547         1
339     52400000031       74671         1
343     52400000031       75076         1
410     52400000031       78851         1
492     52400000031       85176         1
604     52400000031       92018         1
683     52400000031       97991         1
704     52400000031       98720         1
708     52400000031       99835         1
743     52400000031      105146         1
951     52400000031      128047         1
967     52400000031      134954         1
1024    52400000031      204752         1
1049    52400000031      253490         1
1222    52400000031      430360         1
1270    52400000031      452027         1
1553    52400000031      611125         1
1554    52400000031      611930         1
1631    52400000031      649542         1
1747    52400000031      729091         1
1796    52400000031      761787         1
1853    52400000031      807591         1
1854    52400000031      808602         1
2047    52400000031      825249         1
2084    52400000031      826790         1
2106    52400000031      827261         1
2118    52400000031      828278         1
2131    52400000031      828891         1
2188    52400000031      830960         1
2327    52400000031      835715         1
2371    52400000031      837339         1
2692    52400000031      850533         1
2716    52400000031      851226         1
2723    52400000031      851644         1
2727    52400000031      851817         1
2744    52400000031      852864         1
2871    52400000031      858322         1
3164    52400000031      869252         1
3195    52400000031      870372         1
3235    52400000031      871567         1
3369    52400000031      875694         1
3381    52400000031      876593         1
3608    52400000031      885642         1
3685    52400000031      888835         1
3707    52400000031      889774         1
4003    52400000031      901840         1
4229    52400000031      912676         1
4412    52400000031      920112         1
4807    52400000031      933729         1
4827    52400000031      934948         1
5031    52400000031      940108         1
5068    52400000031      942258         1
5187    52400000031      947200         1
5235    52400000031      948665         1
5253    52400000031      949291         1
5663    52400000031      964813         1
5677    52400000031      965557         1
5715    52400000031      966826         1
5784    52400000031      969134         1
5900    52400000031      973693         1
5924    52400000031      974104         1
5973    52400000031      977339         1
6040    52400000031      980644         1
6060    52400000031      982960         1
6070    52400000031      983278         1
6182    52400000031      987941         1
6362    52400000031      996016         1
6594    52400000031     1005583         1
6646    52400000031     1007414         1
6698    52400000031     1009246         1
6798    52400000031     1012427         1
7144    52400000031     1024581         1
7156    52400000031     1025383         1
7302    52400000031     1030409         1
7314    52400000031     1030569         1
7522    52400000031     1039888         1
7541    52400000031     1040744         1
7870    52400000031     1055013         1
7873    52400000031     1055201         1
7902    52400000031     1057227         1
7956    52400000031     1058320         1
7981    52400000031     1059342         1
7993    52400000031     1059930         1
8094    52400000031     1064280         1
8210    52400000031     1067565         1
8287    52400000031     1071625         1
8434    52400000031     1078315         1
8470    52400000031     1079048         1
8745    52400000031     1087960         1
9237    52400000031     1106373         1
9406    52400000031     1112747         1
9502    52400000031     1117061         1
9513    52400000031     1117382         1
9644    52400000031     1122112         1
9675    52400000031     1122876         1
9702    52400000031     1123692         1
9765    52400000031     1126699         1
9872    52400000031     1129538         1
9977    52400000031     1134956         1
10138   52400000031     1144599         1
10329   52400000031     1194726         1
10490   52400000031     1239046         1
10538   52400000031     1249096         1
10597   52400000031     1263632         1
10652   52400000031     1284012         1
10873   52400000031     1349322         1
10940   52400000031     1376453         1
11190   52400000031     1494273         1
11216   52400000031     1524042         1
11287   52400000031     1567164         1
11427   52400000031     1640515         1
11582   52400000031     1728528         1
11632   52400000031     1740348         1
11687   52400000031     1767407         1
11784   52400000031     1804120         1
11833   52400000031     1828277         1
11857   52400000031     1836595         1
11931   52400000031     1855059         1
12044   52400000031     1894894         1
12077   52400000031     1909813         1
12089   52400000031     1917544         1
12145   52400000031     1930720         1
12202   52400000031     1954098         1
12379   52400000031     2042094         1
12458   52400000031     2077731         1
12494   52400000031     2109222         1
12769   52400000031     2453468         1
12799   52400000031     2495440         1
12831   52400000031     2528425         1
12841   52400000031     2538819         1
12864   52400000031     2563513         1
12877   52400000031     2587960         1
12885   52400000031     2594052         1
12930   52400000031     2621630         1
12933   52400000031     2629716         1
12959   52400000031     2644136         1
12960   52400000031     2645397         1
12984   52400000031     2663600         1
13029   52400000031     2688556         1
13141   52400000031     3569014         1
13164   52400000031     3742239         1
13223   52400000031     5131880         1
13365   52400000031     5566545         1
13408   52400000031     5568242         1
16370   52400000031     8249290         1
16375   52400000031     8249440         1
16377   52400000031     8249518         1
17449   52400000031     9526559         1
17587   52400000031     9527175         1
19448   52400000031    12524028         1
19470   52400000031    12524379         1
19491   52400000031    12524774         1
19504   52400000031    12525017         1
19513   52400000031    12525157         1
19521   52400000031    12525264         1
1118    52500000075      328274         1
1122    52500000075      330585         1
1125    52500000075      334648         1
2615    52500000075      847207         1
4002    52500000075      901776         1
6695    52500000075     1009187         1
10519   52500000075     1247341         1
10748   52500000075     1313270         1
11132   52500000075     1441186         1
11336   52500000075     1593899         1
11630   52500000075     1740284         1
12019   52500000075     1887004         1
12443   52500000075     2065971         1
12931   52500000075     2623980         1
14988   52500000075     6978641         1
15050   52500000075     6979545         1
15088   52500000075     6980877         1
15104   52500000075     6981969         1
15120   52500000075     6983062         1
19785   53663271076    13005962         1
19796   53663271076    13007355         1
19799   53663271076    13007356         1
19804   53663271076    13007435         1
19814   53663271076    13007846         1
19841   53663271076    13008334         1
19844   53663271076    13008412         1
19849   53663271076    13009030         1
19853   53663271076    13009718         1
19856   53663271076    13010206         1
19859   53663271076    13010537         1
19862   53663271076    13011457         1
19865   53663271076    13013107         1
19869   53663271076    13013322         1
19875   53663271076    13013786         1
19883   53663271076    13017582         1
19886   53663271076    13017642         1
19889   53663271076    13017741         1
1167    54610030075      392610         1
1393    54610030075      524755         1
1856    54610030075      809486         1
7957    54610030075     1058404         1
9009    54610030075     1096626         1
9919    54610030075     1131382         1
12227   54610030075     1975704         1
14855   54610030075     6564520         1
14948   54610030075     6772755         1
16127   54610030075     8118590         1
17084   54610030075     9423981         1
18355   54610030075     9836386         1
19184   54610030075    12355478         1
19219   54610030075    12384779         1
19807   55100044075    13007499         1
19808   55100044075    13007693         1
19833   55100044075    13008227         1
1221    57265521233      429922         1
1237    57265521233      434543         1
1239    57265521233      434697         1
1241    57265521233      434994         1
1245    57265521233      437011         1
1249    57265521233      438912         1
2215    57265521233      831965         1
2266    57265521233      833350         1
3206    57265521233      870720         1
3415    57265521233      878290         1
4446    57265521233      921197         1
4614    57265521233      927382         1
6872    57265521233     1016210         1
7787    57265521233     1051540         1
8740    57265521233     1087754         1
9887    57265521233     1129945         1
11160   57265521233     1471173         1
11272   57265521233     1559797         1
11341   57265521233     1598259         1
11539   57265521233     1695906         1
11541   57265521233     1698208         1
13463   57265521233     5569852         1
15305   57265521233     7167860         1
15308   57265521233     7167865         1
15322   57265521233     7168233         1
15354   57265521233     7178590         1
15367   57265521233     7188596         1
15373   57265521233     7189963         1
16971   57265521233     9419268         1
17081   57265521233     9423210         1
3479    58978500076      880780         1
4988    58978500076      939864         1
5545    58978500076      959482         1
9192    58978500076     1105635         1
12204   58978500076     1956534         1
20515   58978500076    13382529         1
163     51111074175       61481         2
164     51111074175       61509         2
448     51111074175       82937         2
536     51111074175       86772         2
1261    51111074175      443443         2
1598    51111074175      634296         2
2594    51111074175      846043         2
3421    51111074175      878637         2
3814    51111074175      893258         2
4574    51111074175      925834         2
4959    51111074175      938547         2
5307    51111074175      951971         2
5318    51111074175      952593         2
5567    51111074175      961269         2
5601    51111074175      963226         2
6177    51111074175      987628         2
6905    51111074175     1017841         2
7359    51111074175     1033769         2
7861    51111074175     1054323         2
8102    51111074175     1064945         2
8249    51111074175     1069788         2
10178   51111074175     1148599         2
10363   51111074175     1205634         2
10437   51111074175     1224226         2
10734   51111074175     1308283         2
10907   51111074175     1364467         2
10943   51111074175     1377402         2
10993   51111074175     1398752         2
11006   51111074175     1402844         2
11329   51111074175     1589361         2
11516   51111074175     1687694         2
11691   51111074175     1770601         2
11713   51111074175     1780427         2
12081   51111074175     1912222         2
12133   51111074175     1925691         2
12144   51111074175     1929878         2
12235   51111074175     1984332         2
12408   51111074175     2049074         2
16710   51530011350     9297150         2
16722   51530011350     9297279         2
16737   51530011350     9297509         2
16742   51530011350     9297611         2
16766   51530011350     9304088         2
18695   51530011350    10285023         2
204     52000030042       67573         2
1140    52000030042      369846         2
1527    52000030042      589772         2
2532    52000030042      844413         2
2698    52000030042      850807         2
3160    52000030042      868909         2
3797    52000030042      892556         2
4001    52000030042      901523         2
4009    52000030042      902225         2
4879    52000030042      936741         2
4965    52000030042      939119         2
5390    52000030042      955023         2
5607    52000030042      963562         2
5799    52000030042      969829         2
5860    52000030042      970941         2
7095    52000030042     1023830         2
7648    52000030042     1046131         2
8512    52000030042     1079820         2
8549    52000030042     1080784         2
8758    52000030042     1088544         2
8974    52000030042     1095329         2
9247    52000030042     1106896         2
9678    52000030042     1122889         2
9755    52000030042     1126252         2
9814    52000030042     1127838         2
10497   52000030042     1241890         2
10600   52000030042     1266553         2
10882   52000030042     1351097         2
11013   52000030042     1405927         2
11652   52000030042     1753278         2
11760   52000030042     1798489         2
12112   52000030042     1922592         2
12288   52000030042     2005109         2
12469   52000030042     2088604         2
12693   52000030042     2360149         2
12866   52000030042     2567570         2
13272   52000030042     5564634         2
13273   52000030042     5564713         2
13341   52000030042     5565675         2
13374   52000030042     5567169         2
15406   52000030042     7409880         2
15410   52000030042     7409930         2
15411   52000030042     7409942         2
15415   52000030042     7409997         2
15416   52000030042     7410018         2
15420   52000030042     7410170         2
15423   52000030042     7410216         2
15429   52000030042     7410303         2

In [ ]:
# Thực tế sử dụng coupon
# Ghi nhận các coupon thực tế đã được hộ gia đình đổi thành công khi mua hàng

# household_key: Mã hộ gia đình thực hiện đổi coupon
# .
# day: Ngày giao dịch sử dụng coupon
# .
# coupon_upc: Mã coupon được áp dụng
# .
# campaign: Mã chiến dịch tương ứng với coupon
# .
df_coupon_redempt.head()

   household_key  DAY   COUPON_UPC  CAMPAIGN
0              1  421  10000085364         8
1              1  421  51700010076         8
2              1  427  54200000033         8
3              1  597  10000085476        18
4              1  597  54200029176        18

In [ ]:
# Thông tin quảng cáo & trưng bày tại cửa hàng

# Xác định xem sản phẩm có được xuất hiện trong tờ rơi quảng cáo tuần (weekly mailer) hoặc vị trí trưng bày đặc biệt tại cửa hàng hay không
# .

# product_id: Mã sản phẩm
# .
# store_id: Mã cửa hàng
# .
# week_no: Tuần ghi nhận hoạt động quảng cáo/trưng bày
# .
# display: Vị trí trưng bày sản phẩm tại cửa hàng (ví dụ: Front End Cap, Mid-Aisle End Cap, Rear End Cap, In-Aisle...)
# .
# mailer: Vị trí hình ảnh sản phẩm xuất hiện trên tờ rơi quảng cáo (ví dụ: Trang bìa, trang trong, vị trí ô coupon...)
# .
df_casual_data.head()

   PRODUCT_ID  STORE_ID  WEEK_NO display mailer
0       26190       286       70       0      A
1       26190       288       70       0      A
2       26190       289       70       0      A
3       26190       292       70       0      A
4       26190       293       70       0      A